# change the followings to match your Github username and repo name
baseurl: "/wwwicico" # the name of your github repo
url: "https://tmcat91.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Wild Wild West Internet Company"
description: Innovation

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: tmcat91
author-bio: Founder  # change to false to hide
#author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: false

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "until year 3000"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
